-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE CLIENTE (
IDCLIENTE INT PRIMARY KEY,
ENDEREÇO varchar(100),
EMAIL varchar(50),
TELEFONE varchar(20),
NOME varchar(100)
)

CREATE TABLE PEDIDO (
ID PEDIDO INT PRIMARY KEY,
DATA PEDIDO DATE,
STATUS Texto(1),
IDCLIENTE INT,
FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
)

CREATE TABLE FATURA (
ID FATURA INT PRIMARY KEY,
VALOR TOTAL varchar(20),
DATA DATE,
ID PEDIDO INT,
FOREIGN KEY(ID PEDIDO) REFERENCES PEDIDO (ID PEDIDO)
)

CREATE TABLE ITEM PEDIDO (
ID ITEM PEDIDO INT PRIMARY KEY,
PREÇO varchar(20),
QUANTIDADE varchar(10),
ID PRODUTO INT,
ID PEDIDO INT,
FOREIGN KEY(ID PEDIDO) REFERENCES PEDIDO (ID PEDIDO)
)

CREATE TABLE Entidade_5 (
ID PRODUTO INT PRIMARY KEY,
DESCRIÇÃO varchar(150),
ESTOQUE varchar(50),
NOME vachar(100),
PREÇO varchar(20)
)

ALTER TABLE ITEM PEDIDO ADD FOREIGN KEY(ID PRODUTO) REFERENCES Entidade_5 (ID PRODUTO)
