-- MySQL Script generated by MySQL Workbench
-- Fri Sep 13 08:19:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schemab capitacao
--------------------------------------------------------

--------------------------------------------------------
-- Schema capitacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `capitacao` DEFAULT CHARACTER SET utf8 ;
USE `capitacao` ;

-- -----------------------------------------------------
-- Table `capitacao`.`instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capitacao`.`instrutor` (
  `id_instrutor` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `valorhora` DOUBLE NOT NULL,
  `certificados` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_instrutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capitacao`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `id_curso` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `requisito` VARCHAR(100) NOT NULL,
  `cargaHoraria` DOUBLE NOT NULL,
  `preco` DOUBLE NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capitacao`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capitacao`.`aluno` (
  `id_aluno` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `datanasc` DATE NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capitacao`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capitacao`.`turma` (
  `id_turma` INT NOT NULL,
  `cargaHoraria` DOUBLE NOT NULL,
  `dataInicial` DATE NOT NULL,
  `dataFinal` DATE NOT NULL,
  `instrutor_idInstrutor` INT NOT NULL,
  `instrutor_id_instrutor` INT NOT NULL,
  `curso_idcurso` INT NOT NULL,
  `curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_turma`, `instrutor_id_instrutor`, `curso_id_curso`),
  INDEX `fk_turma_instrutor_idx` (`instrutor_id_instrutor` ASC) VISIBLE,
  INDEX `fk_turma_curso1_idx` (`curso_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_turma_instrutor`
    FOREIGN KEY (`instrutor_id_instrutor`)
    REFERENCES `mydb`.`instrutor` (`id_instrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_curso1`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `mydb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capitacao`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capitacao`.`matricula` (
  `id_matricula` INT NOT NULL,
  `dataMatricula` DATE NOT NULL,
  `matriculacol` VARCHAR(45) NOT NULL,
  `aluno_idaluno` INT NOT NULL,
  `turma_idturma` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  `turma_instrutor_id_instrutor` INT NOT NULL,
  `turma_curso_id_curso` INT NOT NULL,
  `aluno_id_aluno` INT NOT NULL,
  PRIMARY KEY (`id_matricula`),
  INDEX `fk_matricula_turma1_idx` (`turma_id_turma` ASC, `turma_instrutor_id_instrutor` ASC, `turma_curso_id_curso` ASC) VISIBLE,
  INDEX `fk_matricula_aluno1_idx` (`aluno_id_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_matricula_turma1`
    FOREIGN KEY (`turma_id_turma` , `turma_instrutor_id_instrutor` , `turma_curso_id_curso`)
    REFERENCES `mydb`.`turma` (`id_turma` , `instrutor_id_instrutor` , `curso_id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_aluno1`
    FOREIGN KEY (`aluno_id_aluno`)
    REFERENCES `mydb`.`aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
